# Generated by Django 6.1 on 2026-08-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
