# Generated by Django 6.1 on 2026-08-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_URL',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
