# Generated by Django 6.1 on 2026-08-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_URL',
            new_name='image_url',
        ),
    ]
